### PR TITLE
Auto detect target when libmali runs without suffix

### PR DESCRIPTION
**Pull request by kwankiu**
- This allows us to run libmali without adding a suffix by detecting installed path.
- It allows all x11-gbm, wayland-gbm and x11-wayland-gbm to coexist.
- This only apply when libmali is called without a valid suffix. User can still specify a suffix as usual.

This allows us to use `libmali` similar to how `malirun` works on both X and Wayland like:
```
libmali chromium
```

@7Ji @hbiyik FYI.

### CODE REVIEW

**Comment by DarkevilPT** [comment]
Lets keep all options open 🎢

**Comment by hbiyik** [comment]
Could you also bump the pkgrel,
Update the sha256 hashes
And update the srcinfo? I will merge directly

**Comment by hbiyik** [comment]
Or may be even better instead of bumping the pkgrel, you can bump the libmali version, i think g13p0 should be already old

**Comment by 7Ji** [comment]
> Could you also bump the pkgrel, Update the sha256 hashes And update the srcinfo? I will merge directly

Please hold on a sec, there's a few changes I would request, I'll leave them after a few minutes

**Review by 7Ji — CHANGES_REQUESTED** [review]
1. The model should not be hard-coded as mali-valhall-g610 here, it should be %MODEL% so it could be reused for other models and would be replaced during installation into real model, see https://github.com/7Ji-PKGBUILDs/libmali-valhall-g610/blob/4d3f9b9a2dc8021f1f01a6f8e89fd73442593943/libmali-wrapper#L45 , only a few lines after this
2. As we already defined `LIBMALI` to basically `LIBMALI_PATH/TARGET`, `LIBMALI_PATH` could be defined in earlier logic before switch case so in line 45 we could just do `LIBMALI="${LIBMALI_PATH}/${TARGET}"'
3. With the current logic there's no default state. If none of the if-conditions matched then TARGET would be empty. Please either report error and exit explicitly, or set a fallback TARGET in else condition

**Comment by kwankiu** [comment]
> 1. The model should not be hard-coded as mali-valhall-g610 here, it should be %MODEL% so it could be reused for other models and would be replaced during installation into real model, see https://github.com/7Ji-PKGBUILDs/libmali-valhall-g610/blob/4d3f9b9a2dc8021f1f01a6f8e89fd73442593943/libmali-wrapper#L45
>     , only a few lines after this
> 2. As we already defined `LIBMALI` to basically `LIBMALI_PATH/TARGET`, `LIBMALI_PATH` could be defined in earlier logic before switch case so in line 45 we could just do `LIBMALI="${LIBMALI_PATH}/${TARGET}"'
> 3. With the current logic there's no default state. If none of the if-conditions matched then TARGET would be empty. Please either report error and exit explicitly, or set a fallback TARGET in else condition

Done, I didnt realise there is a %MODEL% as I initially edited the script directly on /usr/bin/libmali

**Comment by kwankiu** [comment]
Updated the sha256 hash

**Comment by 7Ji** [comment]
> Or may be even better instead of bumping the pkgrel, you can bump the libmali version, i think g13p0 should be already old

Unfortunately there's no update in the last 9 months and g13p0 is still the latest:

https://github.com/JeffyCN/mirrors/tree/libmali/lib/aarch64-linux-gnu

But I'll bump the pkgrel anyway for the wrapper change

**Pull request merged**
